version: '3.9'

services:
  web:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    env_file: .env
    restart: always
    depends_on:
      - api
  api:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    env_file: /backend/.env
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    ports:
      - 6543:5432
    env_file: .env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    ports:
      - 8181:8080
    env_file: .env
    restart: always

volumes:
  pgdata: {}
